services:
  unmonitarr:
    build: .
    container_name: unmonitarr
    volumes:
      - ./config:/config
      - ./logs:/logs
      - ./unmonitarr.py:/app/unmonitarr.py
    restart: unless-stopped
    environment:
      - TZ=UTC  # Set your timezone
      - MONITOR_MODE=true
      - MONITOR_INTERVAL=3600  # Scan interval in seconds (default: 1 hour)
    command: python unmonitarr.py --config /config/unmonitarr_config.json --monitor
